# Generated by Django 5.2.6 on 2025-09-29 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecyclingCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('opening_hours', models.TextField(help_text='Operating hours information')),
                ('capacity', models.IntegerField(default=100, help_text='Daily capacity')),
                ('current_load', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='centers/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_members', models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'staff'}, to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AcceptedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('plastic', 'Plastic'), ('glass', 'Glass'), ('paper', 'Paper'), ('metal', 'Metal'), ('electronic', 'Electronic'), ('organic', 'Organic'), ('textile', 'Textile'), ('battery', 'Battery'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('recycling_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_materials', to='recycling_centers.recyclingcenter')),
            ],
            options={
                'unique_together': {('recycling_center', 'material_type')},
            },
        ),
    ]
