# Generated by Django 5.2.6 on 2025-09-29 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recycling_centers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecyclingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('plastic', 'Plastic'), ('glass', 'Glass'), ('paper', 'Paper'), ('metal', 'Metal'), ('electronic', 'Electronic'), ('organic', 'Organic'), ('textile', 'Textile'), ('battery', 'Battery'), ('other', 'Other')], max_length=20)),
                ('item_description', models.TextField()),
                ('quantity', models.IntegerField(default=1)),
                ('estimated_weight', models.FloatField(help_text='Weight in kg')),
                ('item_image', models.ImageField(upload_to='requests/')),
                ('additional_images', models.JSONField(blank=True, default=list)),
                ('pickup_address', models.TextField()),
                ('pickup_latitude', models.FloatField(blank=True, null=True)),
                ('pickup_longitude', models.FloatField(blank=True, null=True)),
                ('preferred_pickup_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('staff_notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL)),
                ('recycling_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='recycling_centers.recyclingcenter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycling_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Request Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('pickup_scheduled', 'Pickup Scheduled'), ('picked_up', 'Item Picked Up'), ('processing', 'Processing'), ('completed', 'Recycling Completed'), ('rejected', 'Request Rejected')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='recycling_requests.recyclingrequest')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
