# Generated by Django 5.2.6 on 2025-10-14 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycling_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
